"""empty message

Revision ID: 1006c2f20e0d
Revises: 
Create Date: 2021-04-05 19:01:09.476679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1006c2f20e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('images', sa.String(length=264), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('images')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manga_chapters')
    op.drop_table('manga_details')
    # ### end Alembic commands ###
