"""empty message

Revision ID: bfeffad92bd5
Revises: fdf5c683b7c4
Create Date: 2021-04-07 19:44:45.523721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfeffad92bd5'
down_revision = 'fdf5c683b7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_chap_genre', sa.Column('manga_details_id', sa.Integer(), nullable=False))
    op.drop_constraint('manga_chap_genre_ibfk_1', 'manga_chap_genre', type_='foreignkey')
    op.create_foreign_key(None, 'manga_chap_genre', 'manga_details', ['manga_details_id'], ['id'])
    op.drop_column('manga_chap_genre', 'manga_chap_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_chap_genre', sa.Column('manga_chap_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'manga_chap_genre', type_='foreignkey')
    op.create_foreign_key('manga_chap_genre_ibfk_1', 'manga_chap_genre', 'manga_chapter', ['manga_chap_id'], ['id'])
    op.drop_column('manga_chap_genre', 'manga_details_id')
    # ### end Alembic commands ###
