"""empty message

Revision ID: cee4e2707d80
Revises: 1006c2f20e0d
Create Date: 2021-04-07 19:15:00.199895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee4e2707d80'
down_revision = '1006c2f20e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('issue_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('manga_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_title')
    )
    op.create_table('manga_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_chap_genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_genre_id', sa.Integer(), nullable=False),
    sa.Column('manga_chap_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_chap_id'], ['manga_chapter.id'], ),
    sa.ForeignKeyConstraint(['manga_genre_id'], ['manga_genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga_chap_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_image_id', sa.Integer(), nullable=False),
    sa.Column('manga_chap_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manga_chap_id'], ['manga_chapter.id'], ),
    sa.ForeignKeyConstraint(['manga_image_id'], ['manga_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('images', table_name='manga_chapters')
    op.drop_table('manga_chapters')
    op.drop_column('manga_details', 'title')
    op.drop_column('manga_details', 'genre')
    op.drop_column('manga_details', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_details', sa.Column('rating', mysql.TEXT(), nullable=True))
    op.add_column('manga_details', sa.Column('genre', mysql.TEXT(), nullable=True))
    op.add_column('manga_details', sa.Column('title', mysql.TEXT(), nullable=True))
    op.create_table('manga_chapters',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('images', mysql.VARCHAR(length=264), nullable=True),
    sa.Column('manga_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga_details.id'], name='manga_chapters_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('images', 'manga_chapters', ['images'], unique=True)
    op.drop_table('manga_chap_image')
    op.drop_table('manga_chap_genre')
    op.drop_table('manga_images')
    op.drop_table('manga_genre')
    op.drop_table('manga_chapter')
    # ### end Alembic commands ###
